apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-release.fullname" . }}
  labels:
    {{- include "app-release.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "app-release.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "app-release.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app-release.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.netowrking.container }}
          ports:
            - name: {{ .Values.netowrking.container.name }}
              containerPort:  {{ .Values.netowrking.container.port }}
              protocol: {{ .Values.netowrking.container.protocol }}
          {{- else }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- end }}
          {{- if .Values.monitorConfig.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.monitorConfig.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.monitorConfig.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.monitorConfig.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.monitorConfig.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.monitorConfig.livenessProbe.failureThreshold }}
            {{- if .Values.monitorConfig.livenessProbe.tcpSocket }}
            tcpSocket:
              port: {{ .Values.monitorConfig.livenessProbe.tcpSocket.port }}
            {{- end }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.monitorConfig.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.monitorConfig.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.monitorConfig.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.monitorConfig.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.monitorConfig.readinessProbe.failureThreshold }}
            {{- if .Values.monitorConfig.readinessProbe.httpGet }}
            httpGet:
              path: {{ .Values.monitorConfig.readinessProbe.httpGet.path }}
              port: {{ .Values.monitorConfig.readinessProbe.httpGet.port }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
